In [4]:
import numpy as np
from sklearn.neighbors import NearestNeighbors

In [22]:
samples = [[0, 0, 2], [1, 0, 0], [0, 0, 1]]
neigh = NearestNeighbors(n_neighbors=3, radius=0.4)

In [23]:
neigh.fit(samples)  

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=1, n_neighbors=3, p=2, radius=0.4)

In [25]:
dist, idx = neigh.kneighbors(X=[[0, 0, 1.3]], n_neighbors=3, return_distance=True)

In [26]:
idx

array([[2, 0, 1]])

In [27]:
dist

array([[0.3       , 0.7       , 1.64012195]])

In [28]:
idx[0]

array([2, 0, 1])